config/routes.rb
Rails.application.routes.draw do

match '/contact_us', to: 'pages#contact_us', via: 'post'

root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

   def contact_us
    name = params[:name]
    email = params[:email]
    message = params[:message]

    MyMailer.send_email_contact(name, email, message).deliver_now
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
  
  <title>RT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%#= javascript_include_tag 'gmaps.js' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <%= yield %>
   
</body>

</html>

app/views/pages/_contact_us.html.erb
<section id="contact" class="module">
      <div class="container">

        <div class="row">

          <div class="col-sm-6 col-sm-offset-3">

            <h2 class="module-title font-alt">Get in touch</h2>

          </div>

        </div><!-- .row -->

        <div class="row">

          <div class="col-sm-6 col-sm-offset-3">

            
              <%= form_tag(contact_us_path, method: 'post', multipart: true) do %>
              <div class="form-group">

              	<%= text_field_tag 'name', nil,  class: 'form-control', placeholder: 'Name*'%>
                <p class="help-block text-danger"></p>
              </div>

              <div class="form-group">
                <%= email_field_tag 'email', nil,  class: 'form-control', placeholder: 'Your Email*'%>
                <p class="help-block text-danger"></p>
              </div>

              <div class="form-group">
              	<%= text_area_tag 'message', nil,  class: 'form-control', placeholder: 'Message*'%>
                <p class="help-block text-danger"></p>
              </div>

              <div class="text-center">
                
                <%= button_tag(type: 'submit', class: "btn btn-block btn-round btn-d") do %>
                     Submit
                	<% end %>
              </div>
               <% end %>
           

            <!-- Ajax response -->
            
          </div>

        </div><!-- .row -->

      </div>











    </section>

app/views/pages/home.html.erb
<!-- CSS -->
	<!-- <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="assets/css/simpletextrotator.css" rel="stylesheet">
	<link href="assets/css/font-awesome.min.css" rel="stylesheet">
	<link href="assets/css/et-line-font.css" rel="stylesheet">
	<link href="assets/css/magnific-popup.css" rel="stylesheet">
	<link href="assets/css/flexslider.css" rel="stylesheet">
	<link href="assets/css/owl.carousel.css" rel="stylesheet">
	<link href="assets/css/animate.css" rel="stylesheet">
	<link href="assets/css/style.css" rel="stylesheet">

 -->
	<!-- Preloader -->
	<div class="page-loader">
		<div class="loader">Loading...</div>
	</div>

	<!-- Navigation start -->
	<nav class="navbar navbar-custom navbar-transparent navbar-fixed-top one-page" role="navigation">

		<div class="container">
    
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Reggie Tucker</a>
            </div>
    
            <div class="collapse navbar-collapse" id="custom-collapse">
    
                <ul class="nav navbar-nav navbar-right">
    
                   
    

    


	</nav>
	<!-- Navigation end -->

	<!-- Home start -->
	<section id="home" class="home-section home-parallax home-fade home-full-height bg-dark-30"  data-background="url('/assets/section-3.jpg')" style="height: 252.45px; top: 0px; background-image: url('/assets/section-3.jpg')">

		<div class="hs-caption">
			<div class="caption-content">
				<div class="hs-title-size-4 font-alt mb-30">
                Reggie Tucker
				</div>
				<div class="hs-title-size-3 font-alt mb-40">
					IOS and Ruby on Rails Developer currently for hire..
				</div>
				
				<%=link_to 'Learn More', '#about', class: "section-scroll btn btn-border-w btn-round" %>
			</div>
		</div>

	</section >
	<!-- Home end -->

	<!-- Wrapper start -->
	<div class="main">

		<!-- About start -->
		<section id="about" class="module">
			<div class="container">

				<div class="row">

					<div class="col-sm-8 col-sm-offset-2">

						<h2 class="module-title font-alt">Hello</h2>
						<div class="module-subtitle font-serif large-text">
                           My name is Reggie Tucker and I like making beautiful, solid, secure and tested technology products. I'm a IOS & Full-Stack Ruby on Rails Developer in Cary,NC. I'm self-trained via various intensive IOS & Ruby on Rails course's and I also have a heavy interest in Restful API's used to populated IOS Apps.

						</div>

					</div>

				</div><!-- .row -->

				<div class="row">

					<div class="col-sm-2 col-sm-offset-5">

						<div class="large-text align-center">
							<a href="#features" class="section-scroll"><i class="fa fa-angle-down"></i></a>
						</div>

					</div>

				</div>

			</div><!-- .container -->
		</section>
		<!-- About end -->

		<!-- Divider -->
		<hr class="divider-w">
		<!-- Divider -->

		<!-- Features start -->
		<section id="features" class="module">
			<div class="container">

				<div class="row">

					<div class="col-sm-6 col-sm-offset-3">

						<h2 class="module-title font-alt"> About Me</h2>
						<div class="module-subtitle font-serif">
							I am self employed IOS & Ruby on Rails Developer. Currently I have been working several  production apps  in the Bitcoin industry and Clothing industry. I use Bitbucket for version control and Heroku to deploy, scale, and deliver apps.
						</div>

					</div>

				</div><!-- .row -->

				<div class="row multi-columns-row">

					<!-- Features start -->
					<div class="col-md-4">

						<div class="features-item">
							<div class="features-icon">
								<span class="icon-tools"></span>
							</div>
							<h3 class="features-title font-alt">Skills & Tools</h3>
							Xcode, Xcode plug-ins, Swift, Cocoapods, Carthage, Ruby on Rails, Restful API's HTML, Git, RSpec,  Sketch 3..
						</div>
               
					</div>
					<!-- Features end -->

					<!-- Features start -->
					<div class="col-md-4">

						<div class="features-item">
							<div class="features-icon">
								<span class="icon-bike"></span>
							</div>
							<h3 class="features-title font-alt">Professional Interest</h3>
				 I love building REST APIs using Ruby on Rails. I like to leverage the HTTP protocol to create robust web APIs that can serve different client applications at the same time
						</div>

					</div>
					<!-- Features end -->

					<!-- Features start -->
					<div class="col-md-4">

						<div class="features-item">
							<div class="features-icon">
								<span class="icon-lightbulb"></span>
							</div>
							<h3 class="features-title font-alt">PERSONAL INTERESTS</h3>
							 I enjouy watching Saturday & Sunday afternoon football games. I like to kickback back and turn on redzone While I channel my inner Jack Bauer.. 
						</div>

					</div>
					<!-- Features end -->

					<!-- Features start -->

					<!-- Features end -->

					<!-- Features start -->
					
					<!-- Features end -->

					<!-- Features start -->
					
					<!-- Features end -->

					<!-- Features start -->

					<!-- Features end -->

					<!-- Features start -->

					<!-- Features end -->

				</div><!-- .row -->

			</div><!-- .container -->
		</section>
		<!-- Features end -->

		<!-- Video start -->

		<!-- Video end -->

		<!-- Portfolio start -->
		
		<!-- Portfolio end -->

		<!-- Callout start -->
		<section class="module-small bg-dark">
<div class="container text-center">
				

					

                        
                            <h2 class="callout-title">Update as of September 1st, 2015: I'm ready for a change and something new, and am currently looking for my next full time position (I'm interested only in the Raliegh, NC / Altanta, GA / area, by the way). Get in touch and lets chat!.</h2>
                        

                    
                    
					

				

			</div>
		</section>
		<!-- Callout end -->

		<!-- Alt features start -->

		<!-- Alt features end -->

		<!-- Divider -->
		<hr class="divider-w">
		<!-- Divider -->

		<!-- Team start -->
		<section id="team" class="module">
            <div class="container">

                <div class="row">

                    <div class="col-sm-6 col-sm-offset-3">

                        <h2 class="module-title font-alt">Me</h2>
                        <div class="module-subtitle font-serif">
                            
                        </div>

                    </div>

                </div><!-- .row -->

                <div class="row">

                    <!-- Team item star -->
                    
                    <!-- Team item end -->

                    <!-- Team item star -->
                    
                    <!-- Team item end -->

                    <!-- Team item star -->
                    
                    <!-- Team item end -->

                    <!-- Team item star -->
                    

               <div class="col-xs-4 col-xs-offset-4 center   mb-sm-20 wow fadeInUp">

						<div class="team-item">
							<div class="team-image">
								<%= image_tag "team-2.jpg", :alt =>"" %>
								<div class="team-detail">
									<h5 class="font-alt">Hello</h5>
									<p class="font-serif">You can reach me via facebook or twitter.</p>
									<div class="team-social">
										<a href="#"><i class="fa fa-facebook fa-2x"></i></a>
										<a href="https://twitter.com/ReggieSTucker"><i class="fa fa-twitter fa-2x"></i></a>
									</div>
								</div>
							</div>
							<div class="team-descr font-alt">
								<div class="team-name">Reggie Tucker</div>
								<div class="team-role">IOS/Rails Developer</div>

							</div>
						</div>

					</div>

                    </div>
                    <!-- Team item end -->

                </div><!-- .row -->

            
        </section>
		<!-- Team end -->




		<!-- Count to start -->
		
		<!-- Count to end -->

		<!-- Pricing start -->
		
		<!-- Pricing end -->

		<!-- Testimonials start -->
		<section class="module bg-dark-60 pt-0 pb-0" data-background="/assets/section-7.jpg" style="background-image: url(/assetssection-7.jpg);">

			<div class="testimonials-slider pt-140 pb-140">
				<ul class="slides">

					<!-- Slide 1 start -->
					<li>
						<div class="container">

							<div class="row">

								<div class="col-sm-12">
									<div class="module-icon">
										<span class="icon-quote"></span>
									</div>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-8 col-sm-offset-2">
									<blockquote class="testimonial-text font-alt">Try not to become a man of success, but rather a man of value..</blockquote>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-4 col-sm-offset-4">
									<div class="testimonial-author">
										<div class="testimonial-caption font-alt">
											<div class="testimonial-title">Albert Einstein,</div>
											<div class="testimonial-descr">theoretical physicist</div>
										</div>
									</div>
								</div>

							</div><!-- .row -->

						</div><!-- .container -->
					</li>
					<!-- Slide 1 end -->

					<!-- Slide 2 start -->
					<li>
						<div class="container">

							<div class="row">

								<div class="col-sm-12">
									<div class="module-icon">
										<span class="icon-quote"></span>
									</div>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-8 col-sm-offset-2">
									<blockquote class="testimonial-text font-alt">“Timing, perseverance, and ten years of trying will eventually make you look like an overnight success. Twitter co-founder.</blockquote>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-4 col-sm-offset-4">
									<div class="testimonial-author">
										<div class="testimonial-caption font-alt">
											<div class="testimonial-title">Biz Stone</div>
											<div class="testimonial-descr">Twitter co-founder</div>
										</div>
									</div>
								</div>

							</div><!-- .row -->

						</div><!-- .container -->
					</li>
					<!-- Slide 2 end -->

					<!-- Slide 3 start -->
					<li>
						<div class="container">

							<div class="row">

								<div class="col-sm-12">
									<div class="module-icon">
										<span class="icon-quote"></span>
									</div>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-8 col-sm-offset-2">
									<blockquote class="testimonial-text font-alt">“You don’t learn to walk by following rules. You learn by doing and falling over..</blockquote>
								</div>

							</div><!-- .row -->

							<div class="row">

								<div class="col-sm-4 col-sm-offset-4">
									<div class="testimonial-author">
										<div class="testimonial-caption font-alt">
											<div class="testimonial-title">Sir Richard Branson,</div>
											<div class="testimonial-descr">Virgin Group founder</div>
										</div>
									</div>
								</div>

							</div><!-- .row -->

						</div><!-- .container -->
					</li>
					<!-- Slide 3 end -->

				</ul>
			</div><!-- .testimonials-slider -->

		</section>
		<!-- Testimonials end -->

		<!-- Latest blog posts start -->
		
        <!-- Latest blog posts end -->

		<!-- Subscribe start -->
		<!-- Subscribe end -->

		<!-- Contact start -->
		<%= render 'contact_us' %>
		
		<!-- Divider -->
		<hr class="divider-d">
		<!-- Divider -->
	
		<!-- Footer start -->
		<footer class="footer bg-dark"> 
			<div class="container">
	
				<div class="row">
	
					<div class="col-sm-6">
						<p class="copyright font-alt">© 2015 <a href="index.html">Reggie Tucker</a>, All Rights Reserved.</p>
					</div>
	
					<div class="col-sm-6">
						<div class="footer-social-links">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							
						</div>
					</div>
	
				</div><!-- .row -->
	
			</div>
		</footer>
		<!-- Footer end -->
	
	</div>
	<!-- Wrapper start -->
	
	<!-- Scroll-up -->
	<div class="scroll-up">
		<a href="#totop"><i class="fa fa-angle-double-up"></i></a>
	</div>
	
	<!-- Javascript files -->